pie_diabetico_app/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from django.contrib.auth.decorators import login_required

import views

urlpatterns = patterns(
    '',
    url(
        r'^$',
        login_required(views.IndexView.as_view()),
        name='pie_diabetico_index'
    ),
    url(
        r'^list/(?P<estado>[\w]+)/$',
        login_required(views.HistoriaClinicaListView.as_view()),
        name='historiaclinica_list'
    ),
    url(
        r'^create/$',
        login_required(views.HistoriaClinicaCreateView.as_view()),
        name='historiaclinica_create'
    ),
    url(
        r'^delete/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaDeleteView.as_view()),
        name='historiaclinica_delete'
    ),
    url(
        r'^restore/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaRestore),
        name='historiaclinica_restore'
    ),
    url(
        r'^update/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaUpdateView.as_view()),
        name='historiaclinica_update'
    ),
    url(
        r'^excel/(?P<pk>[\d]+)/$',
        login_required(views.export_to_excel),
        name='historiaclinica_excel'
    ),
    url(
        r'^files/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaAdjuntoList.as_view()),
        name='historiaclinicaadjunto_list'
    ),
    url(
        r'^files/download/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaAdjuntoDownload),
        name='historiaclinicaadjunto_download'
    ),
    url(
        r'^files/delete/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaAdjuntoDeleteView.as_view()),
        name='historiaclinicaadjunto_delete'
    ),
)

neonatologia_analisis_app/models.py
# -*- encoding: utf-8 -*-

import datetime
import os.path

from django.db import models
from django.core.exceptions import ValidationError
from django.utils.encoding import smart_str  # , smart_unicode

from core.models import TimeStampedModel


class DeterminacionEstudioNeonatologia(models.Model):
    nombre = models.CharField(max_length=25)
    descripcion = models.CharField(
        max_length=100,
        blank=True,
        verbose_name="descripción"
    )

    def __str__(self):
        return smart_str(self.nombre)


class EntradaAnalisis(TimeStampedModel):

    # Validators
    def validate_doc_num(value):
        if len(str(value)) < 7:
            raise ValidationError('Debe tener al menos 7 dígitos.')

    def validate_edad(value):
        if len(str(value)) > 3:
            raise ValidationError('Debe tener menos de 4 dígitos.')

    # Meta Datos
    ESTADO_CHOICES = (
        ('A', 'Activo'),
        ('E', 'Eliminado'),
    )
    estado = models.CharField(max_length=1,
                              choices=ESTADO_CHOICES,
                              default='A')
    ETAPA_CHOICES = (
        ('INI', 'Iniciado'),
        ('NTS', 'Notif. Trab. Soc.'),
        ('NOT', 'Notificado'),
        ('COM', 'Completado'),
    )
    etapa = models.CharField(max_length=3,
                             choices=ETAPA_CHOICES,
                             default='INI')

    # Campos Neonatología
    fecha = models.DateField(default=datetime.date.today)
    PRIORIDAD_CHOICES = (
        ('U', 'Urgente'),
        ('N', 'Normal'),
    )
    prioridad = models.CharField(max_length=1,
                                 choices=PRIORIDAD_CHOICES,
                                 default='N')
    SEXO_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    )
    apellido = models.CharField(
        max_length=50,
        verbose_name="apellido"
    )
    nombre = models.CharField(
        max_length=50,
        verbose_name="nombre"
    )
    sexo = models.CharField(
        max_length=1,
        choices=SEXO_CHOICES,
        blank=True,
        verbose_name="sexo"
    )
    fecha_nacimiento = models.DateField(
        verbose_name="fecha nacimiento"
    )
    apellido_madre = models.CharField(
        max_length=50,
        verbose_name="apellido madre"
    )
    nombre_madre = models.CharField(
        max_length=50,
        verbose_name="nombre madre"
    )
    TIPO_DOCS_CHOICES = (
        ('DNI', 'DNI'),
        ('LE', 'LE'),
        ('LC', 'LC'),
        ('CI', 'CI'),
    )
    doc_tipo_madre = models.CharField(
        max_length=3,
        choices=TIPO_DOCS_CHOICES,
        default='DNI',
        verbose_name="doc. tipo madre"
    )
    doc_num_madre = models.IntegerField(
        verbose_name="doc. número madre",
        validators=[validate_doc_num]
    )
    domicilio = models.CharField(
        max_length=100,
        blank=True,
        verbose_name="domicilio"
    )
    telefono = models.CharField(
        max_length=50,
        blank=True,
        verbose_name="teléfono"
    )
    determinaciones = models.ManyToManyField(
        DeterminacionEstudioNeonatologia,
        blank=True,
        verbose_name="determinaciones a repetir"
    )
    muestra_fecha_1 = models.DateField(
        null=True,
        blank=True,
        verbose_name="fecha de primera muestra"
    )
    muestra_num_1 = models.CharField(
        max_length=50,
        blank=True,
        verbose_name="número de primera muestra"
    )

    SINO_CHOICES = (
        ('SI', 'Sí'),
        ('NO', 'No'),
    )
    notificar_trabsoc = models.CharField(
        max_length=2,
        choices=SINO_CHOICES,
        verbose_name="notificar Trabajo Social",
        default='SI',
    )
    neonatologia_obs = models.CharField(
        max_length=500,
        blank=True,
        verbose_name="observaciones"
    )

    # Campos Trabajo Social
    fecha_notif_familia = models.DateField(
        null=True,
        blank=True,
        verbose_name="fecha notificación familia"
    )
    trabsoc_obs = models.CharField(
        max_length=500,
        blank=True,
        verbose_name="observaciones"
    )

    # Campos Laboratorio
    muestra_num_2 = models.CharField(
        max_length=50,
        blank=True,
        verbose_name="número de muestra repetición"
    )
    muestra_fecha_2 = models.DateField(
        null=True,
        blank=True,
        verbose_name="fecha de muestra repetición"
    )
    MUESTRA_TEXTO_CHOICES = (
        ('NOR', 'Normal'),
        ('ALT', 'Alterado'),
    )
    muestra_texto_2 = models.CharField(
        max_length=3,
        choices=MUESTRA_TEXTO_CHOICES,
        blank=True,
        verbose_name="resultado repetición",
    )
    laboratorio_obs = models.CharField(
        max_length=500,
        blank=True,
        verbose_name="observaciones"
    )

    class Meta:
        permissions = (
            ("view_entrada_analisis", "Ver"),
            ("create_entrada_analisis", "Crear"),
            ("change_entrada_analisis_neo", "Modificar neo"),
            ("change_entrada_analisis_trabsoc", "Modificar trabsoc"),
            ("change_entrada_analisis_lab", "Modificar lab"),
            ("delete_entrada_analisis", "Borrar"),
            ("restore_entrada_analisis", "Restaurar")
        )

    def __str__(self):
        return self.fecha.strftime('%d/%m/%Y') +\
            ' ' + smart_str(self.apellido) + ' ' + smart_str(self.nombre)

    def fecha_format(self):
        return self.fecha.strftime('%d/%m/%Y')

    def ape_nom(self):
        return smart_str(self.apellido) + ' ' + smart_str(self.nombre)

    def is_analisis_retraso(self):
        if self.fecha_notif_familia is None:
            return False
        if self.muestra_fecha_2 is not None:
            return False
        dd = datetime.date.today() - self.fecha_notif_familia
        if dd > datetime.timedelta(hours=72):
            return True
        return False

    def get_current_etapa(self):
        # Set etapa
        if not self.muestra_num_2 == '':
            etapa = 'COM'
        elif self.fecha_notif_familia is not None:
            etapa = 'NOT'
        elif self.notificar_trabsoc == 'SI':
            etapa = 'NTS'
        else:
            etapa = 'INI'
        return etapa


def get_upload_path(instance, filename):
    return os.path.join(
        "1", "2", filename
    )


class EntradaAnalisisAdjunto(TimeStampedModel):
    entrada_analisis = models.ForeignKey(EntradaAnalisis, editable=False)

    def get_image_path(self, filename):
        return "neonatologia_analisis_app/entrada_analisis_adjunto/"\
            + str(self.entrada_analisis.id) + "/" + filename

    adjunto = models.FileField(upload_to=get_image_path, null=True)

    class Meta:
        permissions = (
            ("view_entrada_analisis_adjunto", "Ver"),
            ("create_entrada_analisis_adjunto", "Crear"),
            ("delete_entrada_analisis_adjunto", "Borrar")
        )

    def filename(self):
        return os.path.basename(self.adjunto.name)

    def get_file_size(self):
        return self.adjunto._get_size()

    def __str__(self):
        return smart_str(self.entrada_analisis) + ' - ' +\
            smart_str(self.filename())

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Ariel D´Alessandro">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">

    <title>{% block title %}HPR Project{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/dermatologia_project.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->

    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'dermatologia_index' %}">HPR Project</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block top_navbar %}
            <li class="dropdown {% if active = 'pie_diabetico_index' %}active{% endif %}">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-plus-sign"></span> Pie Diabético<b class="caret"></b></a>
              <ul class="dropdown-menu">
                {% if perms.pie_diabetico_app.view_historia_clinica %}
                <li><a href="{% url 'historiaclinica_list' 'activos' %}"><span class="glyphicon glyphicon-list-alt"></span> Listado Fichas</a></li>
                {% endif %}
                {% if perms.pie_diabetico_app.create_historia_clinica %}
                <li><a href="{% url 'historiaclinica_create' %}"><span class="glyphicon glyphicon-plus"></span> Añadir Ficha</a></li>
                {% endif %}
              </ul>
            </li>
            <li class="dropdown {% if active = 'neonatologia_analisis_index' %}active{% endif %}">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-plus-sign"></span> Neonatología Análisis<b class="caret"></b></a>
              <ul class="dropdown-menu">
                {% if perms.neonatologia_analisis_app.view_entrada_analisis %}
                <li><a href="{% url 'entradaanalisis_list' 'todos' %}"><span class="glyphicon glyphicon-list-alt"></span> Listado Pedidos Análisis</a></li>
                {% endif %}
                {% if perms.neonatologia_analisis_app.create_entrada_analisis %}
                <li><a href="{% url 'entradaanalisis_create' %}"><span class="glyphicon glyphicon-plus"></span> Añadir Pedidos Análisis</a></li>
                {% endif %}
              </ul>
            </li>
            {% if user.is_staff %}
            <li><a href="/admin"><span class="glyphicon glyphicon-wrench"></span> Administración</a></li>
            {% endif %}
            {% endblock top_navbar %}
          </ul>
          <ul class="nav navbar-nav pull-right">
            {% if user.is_authenticated %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ request.user }} <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'logout_view' %}">Cerrar sesión</a></li>
                </ul>
            </li>
            {% else %}
            <li><a href="{% url 'login_view' %}">Ingresar</a></li>
            {% endif %}
        </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="starter-template">
        {% block page_title %}{% endblock page_title %}
        {% block content %}{% endblock content %}
      </div>

    </div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block page_title %}
  <h1>HPR Project Index</h1>
{% endblock page_title %}
{% block content %}
  <p class="lead">Bienvenido/a, seleccione una de las aplicaciones en la parte superior.</p>
{% endblock content %}

templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block page_title %}
  <h1>Ingresar</h1>
{% endblock page_title %}

{% block content %}
<div style="padding-top: 20px;">
  {% for error in errors %}
  <div class="alert alert-danger">
    <strong>{{error.label}}</strong> {{error.text}}
  </div>
  {% endfor %}
  {% crispy form %}
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
    window.onload=function() {
    $('#id_username').focus();
}
</script>
{% endblock extra_js %}