neonatologia_analisis_app/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from django.contrib.auth.decorators import login_required

import views

urlpatterns = patterns(
    '',
    url(
        r'^$',
        login_required(views.IndexView.as_view()),
        name='neonatologia_analisis_index'
    ),
    url(
        r'^list/(?P<estado>[\w]+)/$',
        login_required(views.EntradaAnalisisListView.as_view()),
        name='entradaanalisis_list'
    ),
    url(
        r'^create/$',
        login_required(views.EntradaAnalisisCreateView.as_view()),
        name='entradaanalisis_create'
    ),
    url(
        r'^delete/(?P<pk>[\d]+)/$',
        login_required(views.EntradaAnalisisDeleteView.as_view()),
        name='entradaanalisis_delete'
    ),
    url(
        r'^restore/(?P<pk>[\d]+)/$',
        login_required(views.EntradaAnalisisRestore),
        name='entradaanalisis_restore'
    ),
    url(
        r'^import/$',
        login_required(views.EntradaAnalisisExcelImport),
        name='entradaanalisis_import'
    ),
    url(
        r'^update/(?P<pk>[\d]+)/$',
        login_required(views.EntradaAnalisisUpdateView.as_view()),
        name='entradaanalisis_update'
    ),
    url(
        r'^excel/(?P<pk>[\d]+)/$',
        login_required(views.export_to_excel),
        name='entradaanalisis_excel'
    ),
    url(
        r'^files/(?P<pk>[\d]+)/$',
        login_required(views.EntradaAnalisisAdjuntoList.as_view()),
        name='entradaanalisisadjunto_list'
    ),
    url(
        r'^files/download/(?P<pk>[\d]+)/$',
        login_required(views.EntradaAnalisisAdjuntoDownload),
        name='entradaanalisisadjunto_download'
    ),
    url(
        r'^files/delete/(?P<pk>[\d]+)/$',
        login_required(views.EntradaAnalisisAdjuntoDeleteView.as_view()),
        name='entradaanalisisadjunto_delete'
    ),
)

pie_diabetico_app/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

from django.contrib.auth.decorators import login_required

import views

urlpatterns = patterns(
    '',
    url(
        r'^$',
        login_required(views.IndexView.as_view()),
        name='pie_diabetico_index'
    ),
    url(
        r'^list/(?P<estado>[\w]+)/$',
        login_required(views.HistoriaClinicaListView.as_view()),
        name='historiaclinica_list'
    ),
    url(
        r'^create/$',
        login_required(views.HistoriaClinicaCreateView.as_view()),
        name='historiaclinica_create'
    ),
    url(
        r'^delete/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaDeleteView.as_view()),
        name='historiaclinica_delete'
    ),
    url(
        r'^restore/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaRestore),
        name='historiaclinica_restore'
    ),
    url(
        r'^update/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaUpdateView.as_view()),
        name='historiaclinica_update'
    ),
    url(
        r'^excel/(?P<pk>[\d]+)/$',
        login_required(views.export_to_excel),
        name='historiaclinica_excel'
    ),
    url(
        r'^files/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaAdjuntoList.as_view()),
        name='historiaclinicaadjunto_list'
    ),
    url(
        r'^files/download/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaAdjuntoDownload),
        name='historiaclinicaadjunto_download'
    ),
    url(
        r'^files/delete/(?P<pk>[\d]+)/$',
        login_required(views.HistoriaClinicaAdjuntoDeleteView.as_view()),
        name='historiaclinicaadjunto_delete'
    ),
)

neonatologia_analisis_app/models.py
# -*- encoding: utf-8 -*-

import datetime
import os.path

from django.db import models
from django.core.exceptions import ValidationError
from django.utils.encoding import smart_str  # , smart_unicode

from core.models import TimeStampedModel


class DeterminacionEstudioNeonatologia(models.Model):
    nombre = models.CharField(max_length=25)
    descripcion = models.CharField(
        max_length=100,
        blank=True,
        verbose_name="descripción"
    )

    def __str__(self):
        return smart_str(self.nombre)


class EntradaAnalisis(TimeStampedModel):

    # Validators
    def validate_doc_num(value):
        if len(str(value)) < 7:
            raise ValidationError('Debe tener al menos 7 dígitos.')

    def validate_edad(value):
        if len(str(value)) > 3:
            raise ValidationError('Debe tener menos de 4 dígitos.')

    # Meta Datos
    ESTADO_CHOICES = (
        ('A', 'Activo'),
        ('E', 'Eliminado'),
    )
    estado = models.CharField(max_length=1,
                              choices=ESTADO_CHOICES,
                              default='A')
    ETAPA_CHOICES = (
        ('INI', 'Iniciado'),
        ('NTS', 'Notif. Trab. Soc.'),
        ('NOT', 'Notificado'),
        ('COM', 'Completado'),
    )
    etapa = models.CharField(max_length=3,
                             choices=ETAPA_CHOICES,
                             default='INI')

    # Campos Neonatología
    fecha = models.DateField(default=datetime.date.today)
    PRIORIDAD_CHOICES = (
        ('U', 'Urgente'),
        ('N', 'Normal'),
    )
    prioridad = models.CharField(max_length=1,
                                 choices=PRIORIDAD_CHOICES,
                                 default='N')
    SEXO_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    )
    apellido = models.CharField(
        max_length=50,
        verbose_name="apellido"
    )
    nombre = models.CharField(
        max_length=50,
        verbose_name="nombre"
    )
    sexo = models.CharField(
        max_length=1,
        choices=SEXO_CHOICES,
        blank=True,
        verbose_name="sexo"
    )
    fecha_nacimiento = models.DateField(
        verbose_name="fecha nacimiento"
    )
    apellido_madre = models.CharField(
        max_length=50,
        verbose_name="apellido madre"
    )
    nombre_madre = models.CharField(
        max_length=50,
        verbose_name="nombre madre"
    )
    TIPO_DOCS_CHOICES = (
        ('DNI', 'DNI'),
        ('LE', 'LE'),
        ('LC', 'LC'),
        ('CI', 'CI'),
    )
    doc_tipo_madre = models.CharField(
        max_length=3,
        choices=TIPO_DOCS_CHOICES,
        default='DNI',
        verbose_name="doc. tipo madre"
    )
    doc_num_madre = models.IntegerField(
        verbose_name="doc. número madre",
        validators=[validate_doc_num]
    )
    domicilio = models.CharField(
        max_length=100,
        blank=True,
        verbose_name="domicilio"
    )
    telefono = models.CharField(
        max_length=50,
        blank=True,
        verbose_name="teléfono"
    )
    determinaciones = models.ManyToManyField(
        DeterminacionEstudioNeonatologia,
        blank=True,
        verbose_name="determinaciones a repetir"
    )
    muestra_fecha_1 = models.DateField(
        null=True,
        blank=True,
        verbose_name="fecha de primera muestra"
    )
    muestra_num_1 = models.CharField(
        max_length=50,
        blank=True,
        verbose_name="número de primera muestra"
    )

    SINO_CHOICES = (
        ('SI', 'Sí'),
        ('NO', 'No'),
    )
    notificar_trabsoc = models.CharField(
        max_length=2,
        choices=SINO_CHOICES,
        verbose_name="notificar Trabajo Social",
        default='SI',
    )
    neonatologia_obs = models.CharField(
        max_length=500,
        blank=True,
        verbose_name="observaciones"
    )

    # Campos Trabajo Social
    fecha_notif_familia = models.DateField(
        null=True,
        blank=True,
        verbose_name="fecha notificación familia"
    )
    trabsoc_obs = models.CharField(
        max_length=500,
        blank=True,
        verbose_name="observaciones"
    )

    # Campos Laboratorio
    muestra_num_2 = models.CharField(
        max_length=50,
        blank=True,
        verbose_name="número de muestra repetición"
    )
    muestra_fecha_2 = models.DateField(
        null=True,
        blank=True,
        verbose_name="fecha de muestra repetición"
    )
    MUESTRA_TEXTO_CHOICES = (
        ('NOR', 'Normal'),
        ('ALT', 'Alterado'),
    )
    muestra_texto_2 = models.CharField(
        max_length=3,
        choices=MUESTRA_TEXTO_CHOICES,
        blank=True,
        verbose_name="resultado repetición",
    )
    laboratorio_obs = models.CharField(
        max_length=500,
        blank=True,
        verbose_name="observaciones"
    )

    class Meta:
        permissions = (
            ("view_entrada_analisis", "Ver"),
            ("create_entrada_analisis", "Crear"),
            ("change_entrada_analisis_neo", "Modificar neo"),
            ("change_entrada_analisis_trabsoc", "Modificar trabsoc"),
            ("change_entrada_analisis_lab", "Modificar lab"),
            ("delete_entrada_analisis", "Borrar"),
            ("restore_entrada_analisis", "Restaurar")
        )

    def __str__(self):
        return self.fecha.strftime('%d/%m/%Y') +\
            ' ' + smart_str(self.apellido) + ' ' + smart_str(self.nombre)

    def fecha_format(self):
        return self.fecha.strftime('%d/%m/%Y')

    def ape_nom(self):
        return smart_str(self.apellido) + ' ' + smart_str(self.nombre)

    def is_analisis_retraso(self):
        if self.fecha_notif_familia is None:
            return False
        if self.muestra_fecha_2 is not None:
            return False
        dd = datetime.date.today() - self.fecha_notif_familia
        if dd > datetime.timedelta(hours=72):
            return True
        return False

    def get_current_etapa(self):
        # Set etapa
        if not self.muestra_num_2 == '':
            etapa = 'COM'
        elif self.fecha_notif_familia is not None:
            etapa = 'NOT'
        elif self.notificar_trabsoc == 'SI':
            etapa = 'NTS'
        else:
            etapa = 'INI'
        return etapa


def get_upload_path(instance, filename):
    return os.path.join(
        "1", "2", filename
    )


class EntradaAnalisisAdjunto(TimeStampedModel):
    entrada_analisis = models.ForeignKey(EntradaAnalisis, editable=False)

    def get_image_path(self, filename):
        return "neonatologia_analisis_app/entrada_analisis_adjunto/"\
            + str(self.entrada_analisis.id) + "/" + filename

    adjunto = models.FileField(upload_to=get_image_path, null=True)

    class Meta:
        permissions = (
            ("view_entrada_analisis_adjunto", "Ver"),
            ("create_entrada_analisis_adjunto", "Crear"),
            ("delete_entrada_analisis_adjunto", "Borrar")
        )

    def filename(self):
        return os.path.basename(self.adjunto.name)

    def get_file_size(self):
        return self.adjunto._get_size()

    def __str__(self):
        return smart_str(self.entrada_analisis) + ' - ' +\
            smart_str(self.filename())

neonatologia_analisis_app/templates/neonatologia_analisis_app/entradaanalisis_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block page_title %}
{% if title %}
<h1>{{title}}</h1>
{% endif %}
{% endblock page_title %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p class="lead">¿Confirma que desea eliminar "{{ object }}"?</p>
    <button type="submit" class="btn btn-primary">Confirmar</button>
    <a type="button" class="btn btn-default" href={% url 'entradaanalisis_list' 'todos' %}>Cancelar</a>
</form>
{% endblock content %}

neonatologia_analisis_app/templates/neonatologia_analisis_app/entradaanalisis_csv.html
{% autoescape off %}{% for n, v in values %}{{n}}, {{v}}
{% endfor %}{% endautoescape %}

neonatologia_analisis_app/templates/neonatologia_analisis_app/entradaanalisis_detail.html
{% extends "base.html" %}
{% block page_title %}
{% if title %}
<h1>{{title}}</h1>
{% endif %}
{% endblock page_title %}
{% block content %}
  {{object.nombre}}
  {{object.apellido}}
{% endblock content %}

neonatologia_analisis_app/templates/neonatologia_analisis_app/entradaanalisis_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load staticfiles %}

{% block extra_css %}
<link href="{% static 'datepicker/css/datepicker.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block page_title %}
{% if title %}
<h1>{{title}}</h1>
{% endif %}
{% endblock page_title %}

{% block content %}
<div style="padding-top: 20px;">
  {% crispy form %}
</div>
{% endblock content %}

{% block extra_js %}
<script src="{% static 'datepicker/js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $('#id_fecha').datepicker({ format: "dd/mm/yyyy" });
    $('#id_fecha_nacimiento').datepicker({ format: "dd/mm/yyyy" });
    $('#id_muestra_fecha_1').datepicker({ format: "dd/mm/yyyy" });
    $('#id_fecha_notif_familia').datepicker({ format: "dd/mm/yyyy" });
    $('#id_muestra_fecha_2').datepicker({ format: "dd/mm/yyyy" });
  });
</script>
<script type="text/javascript">
  window.onload=function() {
    $('#id_fecha').focus();
  }
</script>
{% endblock extra_js %}

neonatologia_analisis_app/templates/neonatologia_analisis_app/entradaanalisis_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% load staticfiles %}

{% block extra_css %}
<link href="{% static 'datepicker/css/datepicker.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block page_title %}
{% if title %}
<h1>{{title}}</h1>
<h2>{{date|date:"F Y"}}</h2>
{% endif %}
{% endblock page_title %}

{% block content %}

<div class="row">
  <div class="col-sm-12 text-center" style="line-height: 300%;">
    {% for btn in top_btns %}
    <a type="button" class="btn {{btn.class}}" href="{% url btn.url btn.url_args %}"><span class="glyphicon {{btn.icon}} "></span> {{btn.text}}</a>
    {% endfor %}
  </div>
</div>
<div class="row" style="padding-top: 15px; line-height: 300%;">
  <div class="col-xs-5 text-center">
    {% crispy formFechaIr %}
  </div>
  <div class="col-xs-7 text-center">
    {% crispy formBuscar %}
  </div>
</div>

<div class="" style="padding-top: 20px; font-size: 13px;">
  <table class="table table-hover text-left">
    <thead>
      <tr>
        <th>#</th>
        <th>ID</th>
        <th></th>
        <th>Fecha</th>
        <th>Apellido</th>
        <th>Nombre</th>
        <th>Fecha nac.</th>
        <th>Madre Ape.</th>
        <th>Madre Nom.</th>
        <th>Det. a rep.</th>
        <th>Fecha 1º muestra</th>
        <th>Notif. Trab. Soc.</th>
        <th>Fecha notif. flia.</th>
        <th>Fecha muestra rep.</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for entrada in object_list %}
      <tr {% if entrada.estado == 'E' %}class="danger-dark"
          {% elif entrada.etapa == 'COM' %}class="success-dark"
          {% elif entrada.etapa == 'INI' %}class="default"
          {% elif entrada.etapa == 'NTS' %}class="warning-dark"
          {% elif entrada.etapa == 'NOT' %}class="info-dark"
          {%endif%}</tr>
        <td>{{ forloop.counter0 | add:page_obj.start_index }}</td>
        <td>{{entrada.id}}</td>
        <td>{% if entrada.prioridad == 'U' and not entrada.etapa == 'COM' %}<span style="font-size: 15px;" class="glyphicon glyphicon-exclamation-sign blink"></span>{% endif %}
          {% if entrada.is_analisis_retraso %}<span style="font-size: 15px;" class="glyphicon glyphicon-time blink"></span>{% endif %}
        </td>
        <td>{{entrada.fecha|date:"d/m/Y"}}</td>
        <td>{{entrada.apellido}}</td>
        <td>{{entrada.nombre}}</td>
        <td>{{entrada.fecha_nacimiento|date:"d/m/Y"}}</td>
        <td>{{entrada.apellido_madre}}</td>
        <td>{{entrada.nombre_madre}}</td>
        <td><a type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#modal_{{entrada.id}}"><span class="glyphicon glyphicon-list"></span> Ver</a></td>
        <!--Determinaciones modal-->
        <div class="modal fade" id="modal_{{entrada.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h5 class="modal-title" id="myModalLabel"><strong><br>DETERMINACIONES A REPETIR</strong><br><strong>{{entrada.fecha|date:"d/m/Y"}} - {{entrada.apellido}} - {{entrada.nombre}}</strong><h5>
              </div>
              <div class="modal-body text-left">
                {% for determinacion in entrada.determinaciones.all %}
                <h5><span style="font-size: 15px;" class="glyphicon glyphicon-file"></span><strong>{{determinacion.nombre}}</strong></h5>
                {% endfor %}
              </div>
            </div>
          </div>
        </div> <!--/Determinaciones modal-->
        <td>{{entrada.muestra_fecha_1|date:"d/m/Y"}}</td>
        <td>{{entrada.notificar_trabsoc}}</td>
        <td>{{entrada.fecha_notif_familia|date:"d/m/Y"}}</td>
        <td>{{entrada.muestra_fecha_2|date:"d/m/Y"}}</td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
             <span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url 'entradaanalisis_update' entrada.id %}"><span class="glyphicon glyphicon-pencil"></span> Ver/Modificar</a></li>
              <li><a href="{% url 'entradaanalisis_excel' entrada.id %}"><span class="glyphicon glyphicon-arrow-down"></span> Exportar</a></li>
              {% if perms.neonatologia_analisis_app.view_entrada_analisis_adjunto %}
                <li><a href="{% url 'entradaanalisisadjunto_list' entrada.id %}"><span class="glyphicon glyphicon-folder-open"></span> Adjuntos</a></li>
              {% endif %}
              {% if entrada.estado == 'A' and perms.neonatologia_analisis_app.delete_entrada_analisis %}
                <li><a href="{% url 'entradaanalisis_delete' entrada.id %}"><span class="glyphicon glyphicon-remove"></span> Eliminar</a></li>
              {% endif %}
              {% if entrada.estado == 'E' and perms.neonatologia_analisis_app.restore_entrada_analisis %}
                <li><a href="{% url 'entradaanalisis_restore' entrada.id %}"><span class="glyphicon glyphicon-check"></span> Restaurar</a></li>
              {% endif %}
            </ul>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<ul class="pagination">
    {% if page_obj.has_previous %}
    <li><a href="?page={{page_obj.previous_page_number}}">&laquo;</a></li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for pagenum in page_obj.paginator.page_range %}
        {% if pagenum == page_obj.number %}
        <li class="active"><span>{{ pagenum }}<span class="sr-only"></span></span></li>
        {% else %}
        <li><a href="?page={{pagenum}}">{{ pagenum }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li><a href="?page={{page_obj.next_page_number}}">&raquo;</a></li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>

{% endblock content %}

{% block extra_js %}
<script src="{% static 'datepicker/js/bootstrap-datepicker.js' %}"></script>
<script>$('#id_Todos').tooltip()
  $('#id_Todos').tooltip('show')
</script>
<script>
  function init_tipocampo() {
    var campo = $('#id_campoBuscar').val();
    if (campo == 'id' || campo == 'apellido' || campo == 'nombre' || campo == 'apellido_madre' || campo == 'nombre_madre') {
      new_html = "<input class='textinput textInput form-control' id='id_stringBuscar' maxlength='254' name='stringBuscar' type='text'>";
      $('#id_stringBuscar').replaceWith(new_html);
      $('#id_stringBuscar').prop('value', '{{formBuscar.stringBuscar.value}}');
    }
    else if (campo == 'fecha' || campo == 'fecha_nacimiento' || campo == 'muestra_fecha_1' || campo == 'fecha_notif_familia' || campo == 'muestra_fecha_2') {
      new_html = "<input class='textinput textInput form-control' id='id_stringBuscar' maxlength='254' name='stringBuscar' type='text'>";
      $('#id_stringBuscar').replaceWith(new_html);
      $('#id_stringBuscar').datepicker({format: "dd/mm/yyyy"});
      $('#id_stringBuscar').prop('value', '{{formBuscar.stringBuscar.value}}');
    }
    else if (campo == 'notificar_trabsoc') {
      new_html = "<select class='select form-control' id='id_stringBuscar' name='stringBuscar'> <option value='SI'>SI</option> <option value='NO'>NO</option> </select>";
      $('#id_stringBuscar').replaceWith(new_html);
      $('#id_stringBuscar option[value=' + '{{formBuscar.stringBuscar.value}}' + ']').prop('selected', true);
    }
    else if (campo == 'determinaciones') {
      new_html = "<select class='select form-control' id='id_stringBuscar' name='stringBuscar'> {% for det_option in det_options %}<option value='{{det_option.id}}'>{{det_option.nombre}}</option> {% endfor %} </select>";
      $('#id_stringBuscar').replaceWith(new_html);
      $('#id_stringBuscar option[value=' + '{{formBuscar.stringBuscar.value}}' + ']').prop('selected', true);
    }
  };

  $('#id_campoBuscar').change(function() {
    var campo = $('#id_campoBuscar').val();
    if (campo == 'id' || campo == 'apellido' || campo == 'nombre' || campo == 'apellido_madre' || campo == 'nombre_madre') {
      new_html = "<input class='textinput textInput form-control' id='id_stringBuscar' maxlength='254' name='stringBuscar' type='text'>";
      $('#id_stringBuscar').replaceWith(new_html);
      $('#id_stringBuscar').focus();
    }
    else if (campo == 'fecha' || campo == 'fecha_nacimiento' || campo == 'muestra_fecha_1' || campo == 'fecha_notif_familia' || campo == 'muestra_fecha_2') {
      new_html = "<input class='textinput textInput form-control' id='id_stringBuscar' maxlength='254' name='stringBuscar' type='text'>";
      $('#id_stringBuscar').replaceWith(new_html);
      $('#id_stringBuscar').datepicker({format: "dd/mm/yyyy"});
      $('#id_stringBuscar').focus();
      $('#id_stringBuscar').datepicker('show');
    }
    else if (campo == 'notificar_trabsoc') {
      new_html = "<select class='select form-control' id='id_stringBuscar' name='stringBuscar'> <option value='SI'>SI</option> <option value='NO'>NO</option> </select>";
      $('#id_stringBuscar').replaceWith(new_html);
      $('#id_stringBuscar').focus();
    }
    else if (campo == 'determinaciones') {
      new_html = "<select class='select form-control' id='id_stringBuscar' name='stringBuscar'> {% for det_option in det_options %}<option value='{{det_option.id}}'>{{det_option.nombre}}</option> {% endfor %} </select>";
      $('#id_stringBuscar').replaceWith(new_html);
      $('#id_stringBuscar').focus();
    }
  });
</script>
<script type="text/javascript">
  window.onload=function() {
    init_tipocampo();
    $('#id_fechaIr').datepicker({format: "mm/yyyy", viewMode: 1, minViewMode: 1});
  }
</script>
{% endblock extra_js %}

neonatologia_analisis_app/templates/neonatologia_analisis_app/entradaanalisisadjunto_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block page_title %}
{% if title %}
<h1>{{title}}</h1>
{% endif %}
{% endblock page_title %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p class="lead">¿Confirma que desea eliminar "{{ object }}"?</p>
    <button type="submit" class="btn btn-primary">Confirmar</button>
    <a type="button" class="btn btn-default" href={% url 'entradaanalisisadjunto_list' parent_pk %}>Cancelar</a>
</form>
{% endblock content %}

neonatologia_analisis_app/templates/neonatologia_analisis_app/entradaanalisisadjunto_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block page_title %}
{% if title %}
<h1>{{title}}</h1>
{% endif %}
{% endblock page_title %}
{% block content %}
  <div style="padding-top: 20px;">
    {% crispy form %}
  </div>
{% endblock content %}
{% block extra_js %}
{% endblock extra_js %}

neonatologia_analisis_app/templates/neonatologia_analisis_app/entradaanalisisadjunto_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extra_css %}
<style>
  #create_form {padding-top: 15px;}
</style>
{% endblock extra_css %}
{% block page_title %}
{% if title %}
<h2>{{title}}</h2>
<h3>Ficha {{parent_obj.id}} - {{parent_obj.fecha_format}} - {{parent_obj.ape_nom}}</h3>
{% endif %}
{% endblock page_title %}
{% block content %}

{% if error %}
<div class="alert {{ error.class }}">
  <strong>{{ error.title }}</strong> - {{ error.text }}
</div>
{% endif %}

<div id="create_form" class="row">
  {% if perms.neonatologia_analisis_app.create_entrada_analisis_adjunto %}
  {% crispy form %}
  {% endif %}
</div>

<div class="table-responsive">
  <table class="table table-striped table-hover text-left">
    <thead>
      <tr>
        <th>#</th>
        <th>Nombre</th>
        <th>Tamaño</th>
        <th>Fecha</th>
        <th>Creador</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for ea_adjunto in object_list %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ea_adjunto.filename}}</td>
        <td>{{ea_adjunto.get_file_size|filesizeformat}}</td>
        <td>{{ea_adjunto.created|date:"d/m/Y"}}</td>
        <td>{{ea_adjunto.created_user}}</td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
             <span class="glyphicon glyphicon-cog"></span> Acciones <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url 'entradaanalisisadjunto_download' ea_adjunto.id %}"><span class="glyphicon glyphicon-cloud-download"></span> Descargar</a></li>
              {% if perms.neonatologia_analisis_app.delete_entrada_analisis_adjunto %}
              <li><a href="{% url 'entradaanalisisadjunto_delete' ea_adjunto.id %}"><span class="glyphicon glyphicon-remove"></span> Eliminar</a></li>
              {% endif %}
            </ul>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

neonatologia_analisis_app/templates/neonatologia_analisis_app/index.html
{% extends "base.html" %}
{% block page_title %}
  <h1>Neonatología análisis Index</h1>
{% endblock page_title %}